// Copyright (c) 2014-2019 Coin Sciences Ltd
// Meliponariod code distributed under the GPLv3 license, see COPYING file.

#ifndef MELIPONARIOVERSION_H
#define	MELIPONARIOVERSION_H

#define MELIPONARIO_VERSION_MAJOR     1
#define MELIPONARIO_VERSION_MINOR     0
#define MELIPONARIO_VERSION_REVISION  0
#define MELIPONARIO_VERSION_STAGE     2
#define MELIPONARIO_VERSION_BUILD     2

#define MELIPONARIO_PROTOCOL_VERSION 10008
#define MELIPONARIO_PROTOCOL_SUPPORTED "10004 - 10008, 20001"


#ifndef STRINGIZE
#define STRINGIZE(X) DO_STRINGIZE(X)
#endif

#ifndef DO_STRINGIZE
#define DO_STRINGIZE(X) #X
#endif

#define MELIPONARIO_BUILD_DESC_WITH_SUFFIX(maj, min, rev, build, suffix) \
    DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build) "-" DO_STRINGIZE(suffix)

#define MELIPONARIO_BUILD_DESC_FROM_UNKNOWN(maj, min, rev, build) \
    DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build)


#define MELIPONARIO_BUILD_DESC "1.0 beta 2"
#define MELIPONARIO_BUILD_DESC_NUMERIC 10000202


#ifndef MELIPONARIO_BUILD_DESC
#ifdef BUILD_SUFFIX
#define MELIPONARIO_BUILD_DESC MELIPONARIO_BUILD_DESC_WITH_SUFFIX(MELIPONARIO_VERSION_MAJOR, MELIPONARIO_VERSION_MINOR, MELIPONARIO_VERSION_REVISION, MELIPONARIO_VERSION_BUILD, BUILD_SUFFIX)
#else
#define MELIPONARIO_BUILD_DESC MELIPONARIO_BUILD_DESC_FROM_UNKNOWN(MELIPONARIO_VERSION_MAJOR, MELIPONARIO_VERSION_MINOR, MELIPONARIO_VERSION_REVISION, MELIPONARIO_VERSION_BUILD)
#endif
#endif

#define MELIPONARIO_FULL_DESC(build, protocol) \
    "build " build " protocol " DO_STRINGIZE(protocol)


#ifndef MELIPONARIO_FULL_VERSION
#define MELIPONARIO_FULL_VERSION MELIPONARIO_FULL_DESC(MELIPONARIO_BUILD_DESC, MELIPONARIO_PROTOCOL_VERSION)
#endif


#define MELIPONARIO_VERSION_CODE_PROTOCOL_THIS              0
#define MELIPONARIO_VERSION_CODE_PROTOCOL_MIN               1
#define MELIPONARIO_VERSION_CODE_PROTOCOL_MIN_DOWNGRADE     2
#define MELIPONARIO_VERSION_CODE_PROTOCOL_MIN_NO_DOWNGRADE  3
#define MELIPONARIO_VERSION_CODE_PROTOCOL_FOR_RELEVANCE     4
#define MELIPONARIO_VERSION_CODE_BUILD                     16
#define MELIPONARIO_VERSION_CODE_MIN_VALID               1000

#endif	/* MELIPONARIOVERSION_H */

